<?php

namespace SRAG\PegasusHelper\authentication;

use ilAuthSession;
use SRAG\PegasusHelper\audit\AuditLog;

/**
 * Class DefaultUserTokenAuthenticator
 *
 * The user token authenticator is responsible of validating and destroying
 * the auth token as well as authenticate a user by auth-token.
 *
 * The auth-tokens are generated by the "/v2/ilias-app/auth-token" api route.
 * This authenticator logs the user into an ILIAS web session and is used by the
 * `goto.php`/resource-link handlers, which run inside a full ILIAS request that
 * already has a session. It must never be used from `api.php` itself, since that
 * request has no session and must stay stateless (see the zip-download route in
 * {@see \SRAG\PegasusHelper\api\controller\LearningModuleController}, which
 * consumes a token directly via {@see AuthTokenRepository} instead).
 *
 * @author  Nicolas Schäfli <ns@studer-raimann.ch>
 */
final class DefaultUserTokenAuthenticator implements UserTokenAuthenticator
{
    /**
     * @var AuthTokenRepository
     */
    private $tokens;

    /**
     * @var AuditLog
     */
    private $audit;

    public function __construct(AuthTokenRepository $tokens, AuditLog $audit)
    {
        $this->tokens = $tokens;
        $this->audit = $audit;
    }

    /**
     * Authenticates the user with the given token.
     * The token will always be deleted, regardless of the authentication result.
     *
     * @param int       $userId The id of the user which should be logged in.
     * @param string    $token  The token which should be used to authenticate the user with the given id.
     * @param array     $auditContext see {@see UserTokenAuthenticator::authenticate()}
     *
     * @return void
     */
    public function authenticate($userId, $token, array $auditContext = [])
    {
        global $DIC;
        /**
         * @var $ilAuthSession ilAuthSession
         */
        $ilAuthSession = $DIC['ilAuthSession'];
        $user = $DIC->user();

        // The pre-existing session user, if any -- worth recording when it
        // differs from the token's claimed user (e.g. link for user Y opened
        // in a browser already logged in as user X).
        $previousUserId = (int) $user->getId();
        $previousUserId = $previousUserId > 0 ? $previousUserId : null;

        $status = $this->tokens->consume((int) $userId, (string) $token);

        if ($status === AuthTokenRepository::STATUS_CONSUMED) {
            // log in user
            $ilAuthSession->regenerateId();
            $ilAuthSession->setUserId((int) $userId);
            $ilAuthSession->setAuthenticated(true, (int) $userId);

            $user->setId((int) $userId);
            $user->read();

            $this->audit->setActor((int) $userId);
            $this->audit->log(AuditLog::EVENT_SSO_LOGIN, AuditLog::LEVEL_INFO, $auditContext);

            return;
        }

        $reason = $status === AuthTokenRepository::STATUS_EXPIRED ? 'sso_token_expired' : 'sso_token_unknown';
        $level = $reason === 'sso_token_expired' ? AuditLog::LEVEL_INFO : AuditLog::LEVEL_WARNING;

        $fields = $auditContext;
        $fields['reason'] = $reason;
        $fields['claimed_user_id'] = (int) $userId;
        if ($previousUserId !== null && $previousUserId !== (int) $userId) {
            $fields['previous_user_id'] = $previousUserId;
        }

        $this->audit->log(AuditLog::EVENT_SSO_LOGIN_FAILED, $level, $fields);
    }
}
