<?php

namespace SRAG\PegasusHelper\authentication;

use ilAuthSession;

/**
 * Class DefaultUserTokenAuthenticator
 *
 * The user token authenticator is responsible of validating and destroying
 * the auth token as well as authenticate a user by auth-token.
 *
 * The auth-tokens are generated by the "/v2/ilias-app/auth-token" api route.
 * This authenticator logs the user into an ILIAS web session and is used by the
 * `goto.php`/resource-link handlers, which run inside a full ILIAS request that
 * already has a session. It must never be used from `api.php` itself, since that
 * request has no session and must stay stateless (see the zip-download route in
 * {@see \SRAG\PegasusHelper\api\controller\LearningModuleController}, which
 * consumes a token directly via {@see AuthTokenRepository} instead).
 *
 * @author  Nicolas Schäfli <ns@studer-raimann.ch>
 */
final class DefaultUserTokenAuthenticator implements UserTokenAuthenticator
{
    /**
     * @var AuthTokenRepository
     */
    private $tokens;

    public function __construct(AuthTokenRepository $tokens)
    {
        $this->tokens = $tokens;
    }

    /**
     * Authenticates the user with the given token.
     * The token will always be deleted, regardless of the authentication result.
     *
     * @param int       $userId The id of the user which should be logged in.
     * @param string    $token  The token which should be used to authenticate the user with the given id.
     *
     * @return void
     */
    public function authenticate($userId, $token)
    {
        global $DIC;
        /**
         * @var $ilAuthSession ilAuthSession
         */
        $ilAuthSession = $DIC['ilAuthSession'];
        $user = $DIC->user();

        if ($this->tokens->consume((int) $userId, (string) $token)) {
            // log in user
            $ilAuthSession->regenerateId();
            $ilAuthSession->setUserId((int) $userId);
            $ilAuthSession->setAuthenticated(true, (int) $userId);

            $user->setId((int) $userId);
            $user->read();
        }
    }
}
